# Generated by Django 3.0.2 on 2020-02-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rollno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('nnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('teacherid', models.CharField(max_length=20)),
                ('emails', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
