# Generated by Django 3.0.2 on 2020-02-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='emails',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
