# Generated by Django 3.0.2 on 2020-02-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200214_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='nnumber',
            new_name='number',
        ),
    ]
