# Generated by Django 3.0.2 on 2020-02-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200214_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
