# Generated by Django 3.0.2 on 2020-02-20 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200219_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('collegeid', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='clg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.college'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='clg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.college'),
        ),
    ]
