# Generated by Django 3.0.3 on 2020-03-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='video',
            new_name='video1',
        ),
    ]
