# Generated by Django 3.0.3 on 2020-03-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20200318_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
