# Generated by Django 3.0.3 on 2020-02-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200216_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.IntegerField()),
                ('image', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
