# Generated by Django 3.0.3 on 2020-02-20 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_student_clg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='clg',
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300, null=True)),
                ('clg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.college')),
            ],
        ),
    ]
